### ISSUE TITLE
Broken on 7.3

### ISSUE THREAD

**Issue by vincentparrett** [TimGeyssens/BundlingAndMinificationForTheMasses#7]
The package manager complains about HtmlAgilityPack.dll, if I ignore that error, then I get a YSOD - Attempt by security transparent method 'System.Web.Http.GlobalConfiguration.get_Configuration()' to access security critical type 'System.Web.Http.HttpConfiguration' failed.

**Comment by TimGeyssens** [comment]
Fixed with 1.4.0 release
