### ISSUE TITLE
Umbraco 7.3.0 Content "Create" button disappears after installing Optimus 1.4.0

### ISSUE THREAD

**Issue by joelbhansen** [TimGeyssens/BundlingAndMinificationForTheMasses#8]
Where did the "Create" button go?

After installing Optimus 1.4.0 the "Create" button is gone from the Content section of Umbraco 7.3.0

![image](https://cloud.githubusercontent.com/assets/3446836/10660245/cf250506-78a5-11e5-84c1-8d35f080eb73.png)

**Comment by TimGeyssens** [comment]
Hmm it doesn't do anything with the context menu ... so if you uninstall Optimus the create option is back?

**Comment by TimGeyssens** [comment]
Will do a test install to see if I can reproduce

**Comment by TimGeyssens** [comment]
Just tried this on a fresh 7.3 with Optimus 1.4 and the create options doesn't go away so must be something else that is interfering ... are you sure it isn't the user permissions?

**Comment by joelbhansen** [comment]
Hi Tim. Thanks for looking into this.

I've tested again and got the error exactly as before. It is not on a completely clean install though. The problem only comes when Optimus is installed on an Umbraco with Merchello.

This is how I reproduced the error:

1. Created new project in VS2013
2. Installed Umbraco 7.3.0 via NuGet.
3. Installed the Merchello 1.13.0 package through Umbraco. The "Create"-button is still there.
4. Installed the Optimus 1.4.0 package through Umbraco. Now the "Create"-button is gone.

Installing Merchello and Optimus in the opposite order gives the same result.

It seems Merchello 1.13.0 and Optimus 1.4.0 has a compatibility issue.

Uninstalling the Optimus package leaves the project with bad references.

**Comment by TimGeyssens** [comment]
Ok thanks for the additional info, I'll try to reproduce with the steps provided

**Comment by TimGeyssens** [comment]
Do you see any js errors happening?

**Comment by TimGeyssens** [comment]
Just installed latest Merchello and Create is still there... only difference is that I'm not in vs but using webmatrix but doubt it has something todo with that

**Comment by joelbhansen** [comment]
No, I there is no js error. Chrome developer tools reports no errors.

**Comment by TimGeyssens** [comment]
Hmm wel can't reproduce works fine here, any other packages installed?

**Comment by joelbhansen** [comment]
No, that's all. Just the Merchello and Optimus packages.

**Comment by TimGeyssens** [comment]
Ok will see what happens when I install through vis studio

**Comment by joelbhansen** [comment]
I'm sorry for having wasted your time!

I have just made another test directly on the web server with a completely clean test website.

Now the Create button disappears immediately after installing the Merchello package. Not after installing Optimus.

My apologies!

**Comment by TimGeyssens** [comment]
No worries hope you get it sorted :)
